version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: himansh007/word-counter
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=himanshuser
      - MYSQL_PASS=himanshpass
      - MYSQL_DB=word_count
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:3000"
    container_name: word-counter
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=himanshuser
      - MYSQL_PASSWORD=himanshpass 
      - MYSQL_DATABASE=word_count
    container_name: word-counter-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: word-counter-phpmyadmin-app
networks:
  frontend:
  backend: